1. Import the numpy package under the name np 


In [3]:
import numpy as np

2. Print the numpy version and the configuration


In [19]:
print numpy.__version__
np.show_config()


1.13.3
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/Natera/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/Natera/anaconda2/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/Natera/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/Natera/anaconda2/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/Natera/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/Natera/anaconda2/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/Natera/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/Natera/anaconda2/include']


3. Create a null vector of size 10


In [20]:
np.zeros(10)


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

4. How to find the memory size of any array 


In [26]:
my_array = np.zeros(10)
my_array.nbytes


80

5. How to get the documentation of the numpy add function from the command line?


In [35]:
# assume you are in terminal shell;
# now go into python by typing python, hitting enter:
# Franciscos-MacBook-Pro:~ Francisco$ python
import numpy as np
np.info('add')

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add

6. Create a null vector of size 10 but the fifth value which is 1


In [38]:
my_array = np.zeros(10)
my_array[5] = 1
print my_array

[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]


7. Create a vector with values ranging from 10 to 49


In [45]:
my_array = 10 + np.arange(40)
print my_array

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)


In [48]:
my_array = my_array[::-1]
print my_array

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8


In [54]:
my_array = np.arange(9).reshape(3,3)
print my_array

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]


In [55]:
my_array = np.nonzero([1,2,0,0,4,0])
print my_array

(array([0, 1, 4]),)


11. Create a 3x3 identity matrix


In [56]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

12. Create a 3x3x3 array with random values


In [57]:
my_array = np.random.random((3,3,3))
print(my_array)

[[[ 0.25071713  0.93051135  0.00253153]
  [ 0.15257898  0.58133756  0.20556689]
  [ 0.48055772  0.56752093  0.91240941]]

 [[ 0.15008771  0.38623617  0.04915889]
  [ 0.19431732  0.83507617  0.75142659]
  [ 0.90555544  0.7790848   0.94044929]]

 [[ 0.11767898  0.10090492  0.41302681]
  [ 0.68106989  0.45129954  0.94211088]
  [ 0.5390957   0.14492037  0.80766837]]]


13. Create a 10x10 array with random values and find the minimum and maximum values


In [58]:
my_array = np.random.random((10,10))
print my_array.min(), my_array.max()

0.0057486025616 0.99844053186


14. Create a random vector of size 30 and find the mean value


In [59]:
my_array = np.random.random(30)
print my_array.mean()

0.585874684489


15. Create a 2d array with 1 on the border and 0 inside


In [70]:
my_array = np.ones((5,5))
my_array[1:-1, 1:-1] = 0
print my_array


[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


16. How to add a border (filled with 0's) around an existing array?


In [72]:
my_array = np.random.random((5,5))
my_array = np.pad(my_array, pad_width=1, mode='constant', constant_values=0)
print my_array

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


17. What is the result of the following expression?

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [73]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [74]:
my_array = np.diag(1 + np.arange(4), k=-1)
print my_array

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern


In [82]:
my_array = np.zeros((5,5), dtype=int)
my_array[1::2, ::2] = 1
my_array[::2, 1::2] = 1
print my_array

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?


In [84]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function


In [ ]:
my_array = np.tile( np.array([[0,1],[1,0]]), (4,4))
print my_array

22. Normalize a 5x5 random matrix


In [87]:
my_array = np.random.random((5,5))
my_array_max, my_array_min = my_array.max(), my_array.min()
my_array = (my_array - my_array_min) / (my_array_max - my_array_min)
print my_array

[[ 0.04752806  0.72813393  0.77577877  0.56132869  1.        ]
 [ 0.07470689  0.12309366  0.06497657  0.80079303  0.35662968]
 [ 0.96954906  0.05031414  0.26096944  0.53314684  0.34436593]
 [ 0.83284188  0.94022397  0.8279076   0.62178419  0.        ]
 [ 0.87132226  0.94236106  0.95684177  0.54137293  0.02695125]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)


In [91]:
hue = np.dtype([("r", np.ubyte, 1),
               ("g", np.ubyte, 1),
               ("b", np.ubyte, 1),
               ("a", np.ubyte, 1)])

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)


In [89]:
a = np.dot(np.ones((5, 3)), np.ones((3,2)))
print a

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.


In [96]:
a = np.arange(20)
a[ (3 < a) & (a <= 8)] *= -1
print a

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


26. What is the output of the following script?

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


In [97]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


In [101]:
Z**Z
Z <- Z
1j*Z
Z/1/1

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


In [4]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


/Users/Natera/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.
/Users/Natera/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([ -9.22337204e+18])

29. How to round away from zero a float array ?

In [107]:
a = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(a)), a))

[-10.   3.  -6.  -1.   9.   5.   5.  -3.  -8.   5.]


30. How to find common values between two arrays?


In [113]:
a = np.random.randint(0,15,10)
b = np.random.randint(0,15,10)
print a, b
print np.intersect1d(a,b)

[ 3 11  1  6  1  3  7  4  1  6] [11  5 11  1  5  3 14 12  6 13]
[ 1  3  6 11]


31. How to ignore all numpy warnings (not recommended)?


In [ ]:
defaults = np.seterr(all="ignore")

32. Is the following expressions true?

np.sqrt(-1) == np.emath.sqrt(-1)


In [5]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Users/Natera/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

33. How to get the dates of yesterday, today and tomorrow?


In [119]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print yesterday, today, tomorrow

2018-01-10 2018-01-11 2018-01-12


34. How to get all the dates corresponding to the month of July 2016?


In [122]:
print np.arange('2016-07', '2016-08', dtype='datetime64[D]')

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)?


In [125]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. Extract the integer part of a random array using 5 different methods


In [126]:
a = np.random.uniform(0,15,15)
print a

print a - a%1
print np.floor(a)
print np.ceil(a)-1
print a.astype(int)
print (np.trunc(a))

[  6.86716746  14.82955792   5.93985112   5.31146004   0.61023337
  11.15252024  12.68065926  14.82322934   1.01641257   6.13218358
  12.94613171   6.56910227   0.32613622   2.59891478   2.23463485]
[  6.  14.   5.   5.   0.  11.  12.  14.   1.   6.  12.   6.   0.   2.   2.]
[  6.  14.   5.   5.   0.  11.  12.  14.   1.   6.  12.   6.   0.   2.   2.]
[  6.  14.   5.   5.   0.  11.  12.  14.   1.   6.  12.   6.   0.   2.   2.]
[ 6 14  5  5  0 11 12 14  1  6 12  6  0  2  2]
[  6.  14.   5.   5.   0.  11.  12.  14.   1.   6.  12.   6.   0.   2.   2.]


37. Create a 5x5 matrix with row values ranging from 0 to 4


In [127]:
a = np.zeros((5,5))
a += np.arange(5)
print a

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [129]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded


In [130]:
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


40. Create a random vector of size 10 and sort it


In [132]:
a = np.random.random(10)
print a.sort()


None


41. How to sum a small array faster than np.sum?


In [133]:
a = np.arange(10)
np.add.reduce(a)

45

42. Consider two random array A and B, check if they are equal


In [2]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

print np.allclose(A,B)
print np.array_equal(A,B)

NameError: name 'np' is not defined

43. Make an array immutable (read-only)

In [1]:
a = np.zeros(5)
a.flags.writeable = False
a[0] = 1

NameError: name 'np' is not defined

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates


In [146]:
a = np.random.random((10,2))
b, c = a[:,0], a[:,1]
d = np.sqrt( (b**2) + (c**2) )
e = np.arctan2(c, b)
print d
print e

[ 0.986977    0.78602394  0.16725923  0.43412698  0.96489092  0.94809438
  0.73261325  0.63242347  0.70609345  0.18339409] [ 1.25891107  1.40534477  1.01220736  0.68109978  0.02229396  0.20574872
  1.02506397  1.11813484  1.09246696  0.34273292]


45. Create random vector of size 10 and replace the maximum value by 0


In [147]:
a = np.random.random(10)
a[a.argmax()] = 0
print a

[ 0.85230924  0.31999206  0.69018617  0.09851623  0.80788968  0.16652468
  0.32115835  0.09242016  0.          0.32088077]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area


In [150]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)


[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))


In [156]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print np.linalg.det(C)

3638.16363712


48. Print the minimum and maximum representable value for each numpy scalar type


In [154]:
for dtype in [np.int8, np.int32, np.int64]:
   print np.iinfo(dtype).min
   print np.iinfo(dtype).max
for dtype in [np.float32, np.float64]:
   print np.finfo(dtype).min
   print np.finfo(dtype).max
   print np.finfo(dtype).eps


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


49. How to print all the values of an array?


In [153]:
np.set_printoptions(threshold=np.nan)
a = np.zeros((16,16))
print a 

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

50. How to find the closest value (to a given scalar) in a vector?

In [158]:
Z = np.arange(50)
v = np.random.uniform(0,50)
index = (np.abs(Z-v)).argmin()
print(Z[index])

29
